{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 2,
   "id": "97e1f371-2484-4467-a5e0-860f4c08ae75",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Requirement already satisfied: pandas in c:\\users\\ruwey\\anaconda3\\lib\\site-packages (2.3.3)\n",
      "Requirement already satisfied: numpy>=1.26.0 in c:\\users\\ruwey\\anaconda3\\lib\\site-packages (from pandas) (2.3.5)\n",
      "Requirement already satisfied: python-dateutil>=2.8.2 in c:\\users\\ruwey\\anaconda3\\lib\\site-packages (from pandas) (2.9.0.post0)\n",
      "Requirement already satisfied: pytz>=2020.1 in c:\\users\\ruwey\\anaconda3\\lib\\site-packages (from pandas) (2025.2)\n",
      "Requirement already satisfied: tzdata>=2022.7 in c:\\users\\ruwey\\anaconda3\\lib\\site-packages (from pandas) (2025.2)\n",
      "Requirement already satisfied: six>=1.5 in c:\\users\\ruwey\\anaconda3\\lib\\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)\n",
      "Requirement already satisfied: numpy in c:\\users\\ruwey\\anaconda3\\lib\\site-packages (2.3.5)\n",
      "Collecting sklearn.preprocessing\n",
      "  Downloading sklearn_preprocessing-0.1.0-py3-none-any.whl.metadata (70 bytes)\n",
      "Downloading sklearn_preprocessing-0.1.0-py3-none-any.whl (10 kB)\n",
      "Installing collected packages: sklearn.preprocessing\n",
      "Successfully installed sklearn.preprocessing-0.1.0\n"
     ]
    }
   ],
   "source": [
    "!pip install pandas\n",
    "!pip install numpy\n",
    "!pip install sklearn.preprocessing"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 7,
   "id": "5df0afa6-7353-455c-9f75-5c8c44359e15",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "--- Step 1: Loading Dataset ---\n",
      "Dataset Shape: (145, 6)\n",
      "\n",
      "Missing Values Count per Column:\n",
      "Price          0\n",
      "Odometer_km    7\n",
      "Doors          7\n",
      "Accidents      0\n",
      "Location       5\n",
      "Year           0\n",
      "dtype: int64\n",
      "\n",
      "Data Types:\n",
      "Price           object\n",
      "Odometer_km    float64\n",
      "Doors          float64\n",
      "Accidents        int64\n",
      "Location        object\n",
      "Year             int64\n",
      "dtype: object\n",
      "--------------------------------------------------\n",
      "--- Step 2: Dropping Duplicates ---\n",
      "Dropped 5 duplicate row(s).\n",
      "New Shape: (140, 6)\n",
      "--------------------------------------------------\n",
      "--- Step 3: Fixing String Casings ---\n",
      "Unique Locations after fixing casing:\n",
      "['city' 'rural' 'suburb' '??' 'nan' 'subrb']\n",
      "--------------------------------------------------\n",
      "--- Step 4: Imputing Missing Values ---\n",
      "Imputed missing values in 'Odometer_km' with Median: 127701.0\n",
      "Imputed missing values in 'Doors' with Median: 4.0\n",
      "--------------------------------------------------\n",
      "--- Step 5: Handling Outliers via IQR Capping ---\n",
      "--- Step 6: One-Hot Encoding Categorical Variables ---\n",
      "New columns created after One-Hot Encoding:\n",
      "['Location_city', 'Location_nan', 'Location_rural', 'Location_subrb', 'Location_suburb']\n",
      "--------------------------------------------------\n",
      "--- Step 7: Feature Engineering ---\n",
      "Engineered new features: ['CarAge', 'Km_per_year', 'Is_High_Mileage', 'LogPrice']\n",
      "--------------------------------------------------\n",
      "--- Step 8: Feature Scaling ---\n",
      "Scaled continuous features: ['CarAge']\n",
      "\n",
      "Sample of Scaled Features (First 3 rows):\n",
      "     CarAge\n",
      "0  1.686714\n",
      "1 -0.794617\n",
      "2 -0.518913\n",
      "--------------------------------------------------\n",
      "--- Step 9: Final Quality Checks ---\n",
      "Total Missing Values Remaining: 0\n",
      "Sanity Check Passed: No missing values remain.\n",
      "--------------------------------------------------\n",
      "--- Step 10: Saving Cleaned Dataset ---\n",
      "Success! Cleaned and preprocessed data saved to 'clean_car_dataset.csv'.\n",
      "Final Dataset Shape: (140, 12)\n",
      "==================================================\n"
     ]
    }
   ],
   "source": [
    "import pandas as pd\n",
    "import numpy as np\n",
    "from sklearn.preprocessing import StandardScaler\n",
    "\n",
    "# ==============================================================================\n",
    "# STEP 1: LOAD & INSPECT (Soo raridda iyo Baarista Xogta)\n",
    "# ==============================================================================\n",
    "print(\"--- Step 1: Loading Dataset ---\")\n",
    "df = pd.read_csv(\"Downloads/raw_car_dataset.csv\")\n",
    "\n",
    "print(f\"Dataset Shape: {df.shape}\")\n",
    "print(\"\\nMissing Values Count per Column:\")\n",
    "print(df.isnull().sum())\n",
    "print(\"\\nData Types:\")\n",
    "print(df.dtypes)\n",
    "print(\"-\" * 50)\n",
    "\n",
    "\n",
    "# ==============================================================================\n",
    "# STEP 2: DROP DUPLICATES (Ka saaridda Safada Isku Midka Ah)\n",
    "# ==============================================================================\n",
    "print(\"--- Step 2: Dropping Duplicates ---\")\n",
    "initial_rows = df.shape[0]\n",
    "\n",
    "df = df.drop_duplicates()\n",
    "dropped_rows = initial_rows - df.shape[0]\n",
    "\n",
    "print(f\"Dropped {dropped_rows} duplicate row(s).\")\n",
    "print(f\"New Shape: {df.shape}\")\n",
    "print(\"-\" * 50)\n",
    "\n",
    "\n",
    "# ==============================================================================\n",
    "# STEP 3: FIX CATEGORICAL STRING CASING (Hagaajinta Qoraalka Tiirarka)\n",
    "# ==============================================================================\n",
    "print(\"--- Step 3: Fixing String Casings ---\")\n",
    "# Waxaan xaqiijinaynaa in Magacyada Magaalooyinka/Goobaha ay isku qaab u qoran yihiin\n",
    "if 'Location' in df.columns:\n",
    "    df['Location'] = df['Location'].astype(str).str.strip().str.lower()\n",
    "    print(\"Unique Locations after fixing casing:\")\n",
    "    print(df['Location'].unique())\n",
    "print(\"-\" * 50)\n",
    "\n",
    "\n",
    "# ==============================================================================\n",
    "# STEP 4: IMPUTE MISSING VALUES (Buuxinta Xogta Maqan)\n",
    "# ==============================================================================\n",
    "print(\"--- Step 4: Imputing Missing Values ---\")\n",
    "# Tiirarka Nambarada ah waxaan ku buuxinaynaa Median, kuwa Qoraalka ahna Mode\n",
    "numeric_cols = df.select_dtypes(include=[np.number]).columns\n",
    "categorical_cols = df.select_dtypes(include=['object', 'category']).columns\n",
    "\n",
    "# 1. Buuxinta Tiirarka Nambarada ah (Median)\n",
    "for col in numeric_cols:\n",
    "    if df[col].isnull().sum() > 0:\n",
    "        median_val = df[col].median()\n",
    "        df[col] = df[col].fillna(median_val)\n",
    "        print(f\"Imputed missing values in '{col}' with Median: {median_val}\")\n",
    "\n",
    "# 2. Buuxinta Tiirarka Qoraalka ah (Mode)\n",
    "for col in categorical_cols:\n",
    "    if df[col].isnull().sum() > 0:\n",
    "        mode_val = df[col].mode()[0]\n",
    "        df[col] = df[col].fillna(mode_val)\n",
    "        print(f\"Imputed missing values in '{col}' with Mode: '{mode_val}'\")\n",
    "print(\"-\" * 50)\n",
    "\n",
    "\n",
    "# ==============================================================================\n",
    "# STEP 5: OUTLIER HANDLING via IQR CAPPING (Xakamaynta Ciladaha Xogta Nuurka ah)\n",
    "# ==============================================================================\n",
    "print(\"--- Step 5: Handling Outliers via IQR Capping ---\")\n",
    "# Waxaan u sameynaynaa capping xogta aadka u fog iyadoo la isticmaalayo IQR\n",
    "# 1. Ka saar calaamadaha qoraalka ah (haddii ay ku jiraan) oo u beddel lambar\n",
    "if 'Price' in df.columns:\n",
    "    df['Price'] = df['Price'].astype(str).str.replace('$', '').str.replace(',', '')\n",
    "    df['Price'] = pd.to_numeric(df['Price'], errors='coerce')\n",
    "\n",
    "if 'Kilometers_Driven' in df.columns:\n",
    "    df['Kilometers_Driven'] = df['Kilometers_Driven'].astype(str).str.replace(',', '')\n",
    "    df['Kilometers_Driven'] = pd.to_numeric(df['Kilometers_Driven'], errors='coerce')\n",
    "\n",
    "if 'Mileage' in df.columns:\n",
    "    df['Mileage'] = df['Mileage'].astype(str).str.replace(' km/l', '').str.replace(' kmpl', '').str.replace(',', '')\n",
    "    df['Mileage'] = pd.to_numeric(df['Mileage'], errors='coerce')\n",
    "\n",
    "# 2. Hadda sammee loop-kii IQR Capping si caadi ah\n",
    "cols_to_cap = [col for col in ['Price', 'Kilometers_Driven', 'Mileage'] if col in df.columns]\n",
    "\n",
    "for col in cols_to_cap:\n",
    "    Q1 = df[col].quantile(0.25)\n",
    "    Q3 = df[col].quantile(0.75)\n",
    "    IQR = Q3 - Q1\n",
    "    \n",
    "    lower_bound = Q1 - 1.5 * IQR\n",
    "    upper_bound = Q3 + 1.5 * IQR\n",
    "    \n",
    "    # Capping outliers\n",
    "    df[col] = df[col].clip(lower_bound, upper_bound)\n",
    "\n",
    "\n",
    "# ==============================================================================\n",
    "# STEP 6: ONE-HOT ENCODING (U beddelidda Qoraalka Lambaro 0 iyo 1)\n",
    "# ==============================================================================\n",
    "print(\"--- Step 6: One-Hot Encoding Categorical Variables ---\")\n",
    "if 'Location' in df.columns:\n",
    "    # drop_first=True si looga fogaado Dummy Variable Trap\n",
    "    df = pd.get_dummies(df, columns=['Location'], drop_first=True, dtype=int)\n",
    "    print(\"New columns created after One-Hot Encoding:\")\n",
    "    print([col for col in df.columns if 'Location_' in col])\n",
    "print(\"-\" * 50)\n",
    "\n",
    "\n",
    "# ==============================================================================\n",
    "# STEP 7: FEATURE ENGINEERING (Abuurista Tiirar Cusub)\n",
    "# ==============================================================================\n",
    "print(\"--- Step 7: Feature Engineering ---\")\n",
    "current_year = 2026\n",
    "\n",
    "# 1. Abuurista CarAge (Da'da Baabuurka)\n",
    "if 'Year' in df.columns:\n",
    "    df['CarAge'] = current_year - df['Year']\n",
    "\n",
    "# 2. Abuurista Km_per_year (Celcelis ahaanta Kilomitirada Sanadkii)\n",
    "if 'Kilometers_Driven' in df.columns and 'CarAge' in df.columns:\n",
    "    df['Km_per_year'] = df['Kilometers_Driven'] / np.where(df['CarAge'] == 0, 1, df['CarAge'])\n",
    "\n",
    "# 3. Abuurista Is_High_Mileage (Baabuur socday in ka badan 100k)\n",
    "if 'Kilometers_Driven' in df.columns:\n",
    "    df['Is_High_Mileage'] = (df['Kilometers_Driven'] > 100000).astype(int)\n",
    "\n",
    "# 4. Target Cusub: LogPrice (Log transformation ee badbaadiya moodelka)\n",
    "if 'Price' in df.columns:\n",
    "    df['LogPrice'] = np.log1p(df['Price'])\n",
    "\n",
    "print(\"Engineered new features: ['CarAge', 'Km_per_year', 'Is_High_Mileage', 'LogPrice']\")\n",
    "print(\"-\" * 50)\n",
    "\n",
    "\n",
    "# ==============================================================================\n",
    "# STEP 8: FEATURE SCALING (X ONLY) (Isku-miisaamidda Xogta Nambarada ah)\n",
    "# ==============================================================================\n",
    "print(\"--- Step 8: Feature Scaling ---\")\n",
    "# Kaliya continuous features ayaa la scale-gareynayaa (Price iyo LogPrice laguma darayo)\n",
    "features_to_scale = [col for col in ['Kilometers_Driven', 'Mileage', 'Engine', 'Power', 'CarAge', 'Km_per_year'] if col in df.columns]\n",
    "\n",
    "scaler = StandardScaler()\n",
    "df[features_to_scale] = scaler.fit_transform(df[features_to_scale])\n",
    "\n",
    "print(f\"Scaled continuous features: {features_to_scale}\")\n",
    "print(\"\\nSample of Scaled Features (First 3 rows):\")\n",
    "print(df[features_to_scale].head(3))\n",
    "print(\"-\" * 50)\n",
    "\n",
    "\n",
    "# ==============================================================================\n",
    "# STEP 9: FINAL QUALITY CHECKS (Baarista Ugu Dambaysa ee Tayada)\n",
    "# ==============================================================================\n",
    "print(\"--- Step 9: Final Quality Checks ---\")\n",
    "missing_after = df.isnull().sum().sum()\n",
    "print(f\"Total Missing Values Remaining: {missing_after}\")\n",
    "\n",
    "# Assertions si loo hubiyo in aysan jirin wax xog ah oo dhiman\n",
    "assert missing_after == 0, \"Error: Missing values still exist!\"\n",
    "print(\"Sanity Check Passed: No missing values remain.\")\n",
    "print(\"-\" * 50)\n",
    "\n",
    "\n",
    "# ==============================================================================\n",
    "# STEP 10: SAVE CLEANED DATA (Kaydinta Xogta Nadiifta ah)\n",
    "# ==============================================================================\n",
    "print(\"--- Step 10: Saving Cleaned Dataset ---\")\n",
    "output_filename = \"clean_car_dataset.csv\"\n",
    "\n",
    "# Kaydi xogta adigoon index-ka raacinaynin\n",
    "df.to_csv(output_filename, index=False)\n",
    "\n",
    "print(f\"Success! Cleaned and preprocessed data saved to '{output_filename}'.\")\n",
    "print(f\"Final Dataset Shape: {df.shape}\")\n",
    "print(\"=\" * 50)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "c2b2c203-0ec0-4760-9740-b12200e44344",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
